### ISSUE TITLE
cannot sign out from Graasp Compose

### ISSUE THREAD

**Issue by juancarlosfarah** [graasp/graasp-feedback#10]
When I try to sign out from Graasp Compose, I automatically get signed back in.

Steps to Reproduce:

1. Go to Compose
2. Sign in
3. Sign Out

Expected Result

Sign Out

Actual Result

I'm immediately signed back in.

Screen Recording:

https://user-images.githubusercontent.com/1707188/127309137-53a74680-5604-4bae-9051-9728dfcd7dff.mov

**Comment by pyphilia** [comment]
Opened an issue in the related repo https://github.com/graasp/graasp-query-client/issues/40
