### ISSUE TITLE
Info tab on mobile devices

### ISSUE THREAD

**Issue by dgillet** [graasp/graasp-feedback#11]
Once opened, the info tab cannot be removed on small screen, as it hides the buttons

**Comment by spaenleh** [comment]
This issue should be mitigated by using the "chevron" button in the info drawer header. See attached video.

I am closing this for now, but in case this issue persists, please let us know. 

https://github.com/graasp/graasp-feedback/assets/39373170/169b73b7-f6f8-4442-b878-4ab8cef349f8
